In [1]:
!git clone https://github.com/Leejunho123/deep-learning-from-scratch-3.git
%cd /content/deep-learning-from-scratch-3

Cloning into 'deep-learning-from-scratch-3'...
remote: Enumerating objects: 2097, done.
remote: Total 2097 (delta 0), reused 0 (delta 0), pack-reused 2097
Receiving objects: 100% (2097/2097), 32.30 MiB | 26.06 MiB/s, done.
Resolving deltas: 100% (1444/1444), done.
/content/deep-learning-from-scratch-3


In [1]:
!git clone https://github.com/Leejunho123/5G_project.git
%cd /content/5G_project/DeepLearning

Cloning into '5G_project'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 11505 (delta 18), reused 23 (delta 13), pack-reused 11474
Receiving objects: 100% (11505/11505), 245.95 MiB | 28.31 MiB/s, done.
Resolving deltas: 100% (2895/2895), done.
Checking out files: 100% (249/249), done.
/content/5G_project/DeepLearning


## 49 Dataset 클래스와 전처리

### 49.1 Dataset 클래스 구현

In [2]:
import numpy as np
class Dataset:
  def __init__(self, train=True):
    self.train = train
    self.data = None
    self.label = None
    self.prepare()

  def __getitem__(self, index):
    assert np.isscalar(index)
    if self.label is None:
      return self.data[index], None
    else:
      return self.data[index], self.label[index]

  def __len__(self):
    return len(self.data)

  def prepare(self):
    pass

In [4]:
class Spiral(Dataset):
  def prepare(self):
    self.data, self.label = get_spiral(self.train)

In [2]:
import dezero
train_set = dezero.datasets.Spiral(train=True)
print(train_set[0])
print(len(train_set))


(array([-0.13981389, -0.00721657], dtype=float32), 1)
300


### 49.2 큰 데이터셋인 경우

In [6]:
from dezero.datasets import Dataset
import numpy as np
class BigData(Dataset):
  def __getitem__(index):
    x = np.load('data/{}.npy'.format(index))
    t = np.load('label/{}.npy'.format(index))
    return x, t 

  def __len__():
    return 1000000

### 49.3 데이터 이어 붙이기

In [8]:
train_set = dezero.datasets.Spiral()

batch_index = [0,1,2]
batch = [train_set[i] for i in batch_index]

x = np.array([example[0] for example in batch])
t = np.array([example[1] for example in batch])

print(x.shape)
print(t.shape)

(3, 2)
(3,)


In [9]:
batch

[(array([-0.13981389, -0.00721657], dtype=float32), 1),
 (array([0.37049392, 0.5820947 ], dtype=float32), 1),
 (array([ 0.1374263 , -0.17179643], dtype=float32), 2)]

In [10]:
x

array([[-0.13981389, -0.00721657],
       [ 0.37049392,  0.5820947 ],
       [ 0.1374263 , -0.17179643]], dtype=float32)

In [11]:
[example[0] for example in batch]

[array([-0.13981389, -0.00721657], dtype=float32),
 array([0.37049392, 0.5820947 ], dtype=float32),
 array([ 0.1374263 , -0.17179643], dtype=float32)]

In [12]:
[example[1] for example in batch]

[1, 1, 2]

### 49.4 학습 코드

In [6]:
import numpy as np
import dezero
from dezero.models import MLP
import dezero.functions as F
from dezero import optimizers
import math
max_epoch = 300
batch_size = 30
hidden_size = 10
lr = 1.0

train_set = dezero.datasets.Spiral()
model = MLP((hidden_size,10))
optimizer = optimizers.SGD(lr).setup(model)

data_size = len(train_set)
max_iter = math.ceil(data_size / batch_size)

for epoch in range(max_epoch):
  index = np.random.permutation(data_size)
  sum_loss = 0
  for i in range(max_iter):

    batch_index = index[i * batch_size:(i+1) * batch_size]
    batch = [train_set[i] for i in batch_index]
    batch_x = np.array([example[0] for example in batch])
    batch_t = np.array([example[1] for example in batch])

    y = model(batch_x)
    loss = F.softmax_cross_entropy(y, batch_t)

    model.cleargrads()
    loss.backward()
    optimizer.update()

    sum_loss += float(loss.data) * len(batch_t)

  avg_loss = sum_loss /data_size
  print('epoch %d, loss %.2f' % (epoch + 1 , avg_loss))

epoch 1, loss 1.35
epoch 2, loss 1.06
epoch 3, loss 0.98
epoch 4, loss 0.90
epoch 5, loss 0.88
epoch 6, loss 0.84
epoch 7, loss 0.84
epoch 8, loss 0.81
epoch 9, loss 0.79
epoch 10, loss 0.77
epoch 11, loss 0.80
epoch 12, loss 0.77
epoch 13, loss 0.76
epoch 14, loss 0.76
epoch 15, loss 0.76
epoch 16, loss 0.76
epoch 17, loss 0.76
epoch 18, loss 0.80
epoch 19, loss 0.78
epoch 20, loss 0.77
epoch 21, loss 0.76
epoch 22, loss 0.74
epoch 23, loss 0.79
epoch 24, loss 0.77
epoch 25, loss 0.75
epoch 26, loss 0.77
epoch 27, loss 0.77
epoch 28, loss 0.74
epoch 29, loss 0.77
epoch 30, loss 0.75
epoch 31, loss 0.75
epoch 32, loss 0.77
epoch 33, loss 0.74
epoch 34, loss 0.75
epoch 35, loss 0.76
epoch 36, loss 0.74
epoch 37, loss 0.80
epoch 38, loss 0.73
epoch 39, loss 0.74
epoch 40, loss 0.74
epoch 41, loss 0.78
epoch 42, loss 0.75
epoch 43, loss 0.72
epoch 44, loss 0.74
epoch 45, loss 0.71
epoch 46, loss 0.72
epoch 47, loss 0.74
epoch 48, loss 0.71
epoch 49, loss 0.71
epoch 50, loss 0.71
epoch 51,

### 49.5 데이터셋 전처리

In [ ]:
class Dataset:
  def __init__(self, train=True, transform=None, target_transform=None):
    self.train = train
    self.transform = transform
    self.target_transform = target_transform
    if self.tranform is None:
      self.tranform = lambda x: x
    if self.target_transform is None:
      self.target_transform = lambda x: x

    self.data = None
    self.label = None
    self.prepare()

  def __getitem__(self, index):
    assert np.isscalar(index)
    if self.label is None:
      return self.transform(self.data[index]), None

    else:
      return self.transform(self.data[index]), self.target_transform(self.label[index])

  def __len__(self):
    return len(self.data)

  def prepare(self):
    pass

    

In [14]:
def f(x):
  y = x / 2.0
  return y

train_set = dezero.datasets.Spiral(transform=f)

In [15]:
import dezero.datasets
from dezero import transforms 

f = transforms.Normalize(mean=0.0, std=2.0)
train_set = dezero.datasets.Spiral(transform=f)


In [17]:
f = transforms.Compose([transforms.Normalize(mean=0.0, std=2.0), transforms.AsType(np.float64)])