In [1]:
!git clone https://github.com/Leejunho123/5G_project.git
%cd 5G_project/DeepLearning

Cloning into '5G_project'...
remote: Enumerating objects: 229, done.
remote: Counting objects: 100% (229/229), done.
remote: Compressing objects: 100% (145/145), done.
remote: Total 11257 (delta 169), reused 135 (delta 83), pack-reused 11028
Receiving objects: 100% (11257/11257), 245.92 MiB | 30.35 MiB/s, done.
Resolving deltas: 100% (2707/2707), done.
Checking out files: 100% (245/245), done.
/content/5G_project/DeepLearning


## 40 브로드캐스트 함수

### 40.1 broadcast_to 함수와 sum_to 함수(넘파이 버전)

In [ ]:
import numpy as np

x = np.array([1,2,3])
y = np.broadcast_to(x,(2,3))
print(y)

[[1 2 3]
 [1 2 3]]


In [2]:
import numpy as np
from dezero.utils import sum_to

x = np.array([[1,2,3],[4,5,6]])
y = sum_to(x, (1,3))
print(y)

y = sum_to(x,(2,1))
print(y)

[[5 7 9]]
[[ 6]
 [15]]


### 40.2 broadcast_to 함수와 sum_to 함수 (DeZero 버전)

In [ ]:
class BroadcastTo(Function):
  def __init__(self, shape):
    self.shape = shape

  def forward(self, x):
    self.x_shape = x.shape
    y = np.broadcast_to(x, self.shape)
    return y

  def backward(self, gy):
    gx = sum_to(gy, self.x_shape)
    return gx


def broadcast_to(x, shape):
  if x.shape == shape:
    return as_variable(x)
  
  return BroadcastTo(shape)(x)

In [ ]:
from dezero import utils

class SumTo(Function):
  def __init__(self, shape):
    self.shape = shape

  def forward(self, x):
    self.x_shape = x.shape
    y = utils.sum_to(x, self.shape)
    return y

  def backward(self, gy):
    gx = broadcast_to(gy, self.x_shape)
    return gx

def sum_to(x, shape):
  if x.shape == shape:
    return as_variable(x)

  return SumTo(shape)

### 40.3 브로드캐스트 대응

In [ ]:
x0 = np.array([1,2,3])
x1 = np.array([10])
y = x0+x1
print(y)

[11 12 13]


In [3]:
from dezero import Variable

x0 = Variable(np.array([1,2,3]))
x1 = Variable(np.array([10]))
y = x0 + x1
print(y)



variable([11 12 13])


In [8]:
from dezero import functions

y.backward()
print(x1.grad)


variable([3])
