In [2]:
!git clone https://github.com/Leejunho123/5G_project.git
%cd 5G_project/DeepLearning

fatal: destination path 'deep-learning-from-scratch-3' already exists and is not an empty directory.
[Errno 2] No such file or directory: 'deep-learning-from-scrath-3'
/content


## 47 소프트맥스 함수와 교차 엔트로피 오차

### 47.1 슬라이스 조작함수

In [5]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array([[1,2,3],[4,5,6]]))
y = F.get_item(x, 1)
print(y)

variable([4 5 6])


In [6]:
y.backward()
print(x.grad)

variable([[0 0 0]
          [1 1 1]])


In [ ]:
x = Variable(np.array([[1,2,3],[4,5,6]]))
indices = np.array([0,0,1])
y = F.get_item(x, indices)
print(y)


variable([[1 2 3]
          [1 2 3]
          [4 5 6]])


In [ ]:
Variable.__getitem__ = F.get_item

y = x[1]
print(y)

y = x[:,2]
print(y)



variable([4 5 6])
variable([3 6])


### 47.2 소프트맥스 함수

In [ ]:
from dezero.models import MLP
model = MLP((10,3))


In [ ]:
x = np.array([[0.2,-0.4]])
y = model(x)
print(y)

variable([[-0.16664435 -0.29604264  0.82092407]])


In [ ]:
from dezero import Variable, as_variable
import dezero.functions as F

def softmax1d(x):
  x = as_variable(x)
  y = F.exp(x)
  sum_y = F.sum(y)
  return y / sum_y

In [ ]:
x = Variable(np.array([[0.2,-0.4]]))
y = model(x)
p = softmax1d(y)
print(y)
print(p)

variable([[-0.16664435 -0.29604264  0.82092407]])
variable([[0.21913858 0.19254041 0.58832101]])


In [ ]:
def softmax_simple(x, axis=1):
  x = as_variable(x)
  y = exp(x)
  sum_y = sum(y, axis=axis, keepdims=True)
  return y/ sum_y

  

### 47.3 교차 엔트로피 오차

In [ ]:
def softmax_cross_entropy_simple(x, t):
  x, t = as_variable(x), as_variable(t)
  N = x.shape[0]
  p = softmax(x)
  p = clip(p, 1e-15, 1.0)
  log_p = log(p)
  tlog_p = log_p[np.arange(N), t.data]
  y = -1 * sum(tlog_p) / N
  return y


In [ ]:
x = np.array([[0.2,-0.4],[0.3,0.5],[1.3,-3.2],[2.1,0.3]])
t = np.array([2,0,1,0])
y = model(x)
loss = F.softmax_cross_entropy_simple(y,t)
print(loss)

NameError: ignored