In [1]:
!git clone https://github.com/Leejunho123/5G_project.git
%cd 5G_project/DeepLearning/

Cloning into '5G_project'...
remote: Enumerating objects: 207, done.
remote: Counting objects: 100% (207/207), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 11235 (delta 152), reused 120 (delta 74), pack-reused 11028
Receiving objects: 100% (11235/11235), 245.92 MiB | 31.20 MiB/s, done.
Resolving deltas: 100% (2690/2690), done.
Checking out files: 100% (245/245), done.
/content/5G_project/DeepLearning


## 38 형상 변환 함수

### 38.1 reshape 함수 구현

In [ ]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
y = np.reshape(x, (6,))
print(y)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
from dezero import Function

class Reshape(Function):
  def __init__(self, shape):
    self.shape = shape

  def forward(self, x):
    self.x_shape = x.shape
    y = x.reshaep(self.shape)
    return y

  def backward(self, gy):
    return reshape(gy, self.x_shape)
    

In [ ]:
from dezero.core import as_variable

In [ ]:
def reshape(x, shape):
  if x.shape == shape:
    return as_variable(x)
  
  return Reshape(shape)(x)

In [ ]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array([[1,2,3],[4,5,6]]))
y = F.reshape(x, (6,))
y.backward(retain_grad=True)
print(x.grad)
print(y)

variable([[1 1 1]
          [1 1 1]])
variable([1 2 3 4 5 6])


### 38.2 Variable에서 reshape 사용하기

+ $2^{2}+2^{2}= 8$
+ Variable reshape 추가

In [ ]:
x = np.random.rand(1,2,3)
y = x.reshape((2,3))
y = x.reshape([2,3])
y = x.reshape(2,3)



In [ ]:
import dezero

def reshape(self, *shape):
  if len(shape) == 1 and isinstance(shape[0], (tuple, list)):
    shape = shape[0]
  return dezero.functions.reshape(self, shape)

In [ ]:
x = Variable(np.random.randn(1,2,3))
y = x.reshape((2,3))
y = x.reshape(2,3)

### 38.3 행렬의 전치

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.transpose(x)
print(y)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
class Transpose(Function):
  def forward(self, x):
    y = np.transpose(x)
    return y

  def backward(self, gy):
    gx = transpose(gy)
    return gx

def transpose(x):
  return Transpose()(x)

In [2]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array([[1,2,3], [4,5,6]]))
y = F.transpose(x)
y.backward()
print(x.grad)

variable([[1 1 1]
          [1 1 1]])


In [10]:
x = Variable(np.random.rand(2,3))
y = x.transpose()
y = x.T
y

variable([[0.52072708 0.16334141]
          [0.74540706 0.9956255 ]
          [0.93425746 0.05012346]])

### 38.4 실제 transpose 함수

In [12]:
A, B, C, D = 1, 2, 3, 4
x = np.random.rand(A,B,C,D)
y = x.transpose(1,0,3,2)

In [13]:
print(y)

[[[[0.5692195  0.17055055 0.8477798 ]
   [0.00404037 0.64476853 0.75027315]
   [0.87914125 0.92483477 0.44197465]
   [0.3682143  0.83506006 0.87639281]]]


 [[[0.38260575 0.77055426 0.096288  ]
   [0.14650661 0.91571985 0.43126466]
   [0.37220213 0.12957159 0.92941875]
   [0.76641994 0.69980804 0.97292472]]]]


In [14]:
print(x)

[[[[0.5692195  0.00404037 0.87914125 0.3682143 ]
   [0.17055055 0.64476853 0.92483477 0.83506006]
   [0.8477798  0.75027315 0.44197465 0.87639281]]

  [[0.38260575 0.14650661 0.37220213 0.76641994]
   [0.77055426 0.91571985 0.12957159 0.69980804]
   [0.096288   0.43126466 0.92941875 0.97292472]]]]
