In [1]:
!git clone https://github.com/Leejunho123/5G_project.git
%cd 5G_project/DeepLearning

Cloning into '5G_project'...
remote: Enumerating objects: 229, done.
remote: Counting objects: 100% (229/229), done.
remote: Compressing objects: 100% (145/145), done.
remote: Total 11257 (delta 169), reused 135 (delta 83), pack-reused 11028
Receiving objects: 100% (11257/11257), 245.92 MiB | 30.43 MiB/s, done.
Resolving deltas: 100% (2707/2707), done.
Checking out files: 100% (245/245), done.
/content/5G_project/DeepLearning


## 39 합계 함수

### 39.1 sum 함수의 역전파

### 39.2 sum 함수 구현

In [ ]:
class Sum(Function):
  def forward(self, x):
    self.x_shape = x.shape
    y = x.sum()
    return y

  def backward(self, gy):
    #boradcast_to 함수 당겨씀
    gx = broadcast_to(gy, self.x_shape)
    return gx

def sum(x):
  return Sum()(x)




In [2]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array([1,2,3,4,5,6]))
y = F.sum(x)
y.backward()
print(y)
print(x.grad)

variable(21)
variable([1 1 1 1 1 1])


### 39.3 axis 와 keepdims

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.sum(x, axis=0)
print(y)
print(x.shape, ' -> ', y.shape)


[5 7 9]
(2, 3)  ->  (3,)


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.sum(x, keepdims=True)
print(y)
print(y.shape)

[[21]]
(1, 1)


+ axis와 keepdims 추가

In [ ]:
from dezero import utils

class Sum(Function):
  def __init__(self, axis, keepdims):
    self.axis = axis
    self.keepdims = keepdims

  def forward(self, x):
    self.x_shape = x.shape
    y = x.sum(axis=self.axis, keepdims=self.keepdims)
  
  def backward(self, gy):
    gy = utils.reshape_sum_backward(gy, self.x_shape, self.axis, self.keepdims)

    gx = broadcast_to(gy, self.x_shape)
    return gx

def sum(x, axis=None, keepdims=False):
  return Sum(axis, keepdims)(x)

In [ ]:
class Variable:
  ---

  def sum(self, axis=None, keepdims=False):
    return dezero.functions.sum(self, axis, keepdims)
    

In [4]:
x = Variable(np.array([[1,2,3],[4,5,6]]))
y = F.sum(x, axis=0)
y.backward()
print(y)
print(x.grad)

x = Variable(np.random.rand(2,3,4,5))
print(x)
y = x.sum(keepdims=True)
print(y)
print(y.shape)

variable([5 7 9])
variable([[1 1 1]
          [1 1 1]])
variable([[[[0.86353304 0.43526907 0.06459079 0.04308734 0.89846502]
            [0.07924463 0.58700658 0.20343856 0.2735073  0.22359391]
            [0.26602262 0.66987979 0.88332644 0.23978538 0.84723193]
            [0.26088459 0.43641095 0.7297572  0.91685689 0.92721243]]
         
           [[0.89161075 0.07625754 0.13426826 0.81019018 0.554242  ]
            [0.13955564 0.62726214 0.21836155 0.11933354 0.98127834]
            [0.99165997 0.42048108 0.11970186 0.11198229 0.83177195]
            [0.40838893 0.75107959 0.18018779 0.99045405 0.28586786]]
         
           [[0.0259888  0.04908306 0.59793292 0.51482172 0.35692383]
            [0.35019362 0.25743077 0.94844402 0.51654799 0.94635615]
            [0.47163116 0.83485453 0.72158374 0.16218402 0.02473214]
            [0.03526695 0.59531609 0.87458517 0.75610948 0.58729737]]]
         
         
          [[[0.61817676 0.74315734 0.71674045 0.2645765  0.01866427]
   